services:
  soumetsu-api:
    image: soumetsu-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    environment:
      - APP_HTTP_HOST=0.0.0.0
      - APP_HTTP_PORT=80
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=mysql
      - APP_COMPONENT=fastapi
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    env_file:
      - ./configuration/app.env
      - ./configuration/mysql.env
    volumes:
      - ${STORAGE_PATH}:/data
    healthcheck:
      test: "curl --fail http://localhost/api/v2/health/"
      interval: 10s
      timeout: 1s
      retries: 2
